Added COUNTA
Lido-App/fast-formula-parser pull request #11
Opened 2021-09-27 19:32 UTC by Randymations

Added the COUNTA spreadsheet function

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2021-09-27 19:33 UTC, tyleradams approved these changes

2021-09-27 19:37 UTC, nathanburgess requested changes
Code formatting nit and then gtg

2021-09-27 19:37 UTC, nathanburgess commented on formulas/functions/statistical.js
> +    },
Indentation looks a little off here.

2021-10-06 21:33 UTC, nathanburgess commented
> is this good to merge?

Could use some formatting but it’s good to go functionally. Formatting doesn’t really matter as it’s all going to be fixed when we mono-repo.

2021-10-10 23:38 UTC, merged