Lido app/marcus/xlookup
Lido-App/fast-formula-parser pull request #13
Opened 2021-10-25 23:52 UTC by marhong2

Draft for @tyleradams, All questions are labeled as @TYLER . The main issues I am having is what should Filter return (RN it is an array of arrays) and if that is correct, how do I test it?

Thank you! 
Marcus

2021-10-30 01:05 UTC, marhong2 commented on formulas/helpers.js
> +            var min_Index = Math.min(lookup_value.length, compare_value.length);
I rewrote the documentation, it should also give the magnitude of difference. This way I can implement the comparison based match modes. E.g. if I want to compare a and b, not only should it be a negative number, but should also return a number of smaller magnitude than a compared to z. This allows me to do comparisons for search mode 1 and -1! I see that the magnitude is not needed for BS so I'll implement your changes locally in XLOOKUP

2021-10-30 01:07 UTC, marhong2 commented on formulas/helpers.js
> +            var min_Index = Math.min(lookup_value.length, compare_value.length);
I think, locale compare only returns a value based upon their difference, not including their magnitude...

2021-10-31 01:04 UTC, tyleradams requested changes
Overall this is more complicated than we'd like which makes it hard to validate correctness.

However, if you can show screenshots where excel's xlookup returns the same values as this, it's fine by me.

2021-10-31 01:04 UTC, tyleradams commented on test/formulas/reference/testcase.js
> +        //match_mode = 0 and searc_mode is 1
Good comments! Fix typos

2021-10-31 02:51 UTC, marhong2 commented
I have double checked all formulas against excel up as I have been working!

2021-10-31 02:52 UTC, tyleradams commented
Excellent!


On Sat, Oct 30, 2021 at 10:51 PM marhong2 ***@***.***> wrote:

> I have double checked all formulas against excel up as I have been working!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Lido-App/fast-formula-parser/pull/13#issuecomment-955627309>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDXQYNG6REKLMJUAVSY5M3UJSVMHANCNFSM5GWOQGEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-02 00:34 UTC, tyleradams commented
> Would you like me to keep a catalog from here on out?
Just sign off that you verified them all against excel at the end.

> Also, excel does a weird thing where it doesn't think the string ".55" equals the number 0.55. Would you like me to mimic excel, or make it so that in Lido this comparison would be true?

Yeah, spreadsheet data values have types. We should respect that too.

2021-11-03 23:12 UTC, marhong2 commented on formulas/helpers.js
> +        //the special cases with the unique regex values
Just to confirm, I should not implement ~ and instead use the wildcard-match library listed?

2021-11-03 23:22 UTC, tyleradams commented on formulas/helpers.js
> +        //the special cases with the unique regex values
I was making a more subtle point, let's just ignore it so we can get this merged.

2021-11-04 08:36 UTC, marhong2 commented on formulas/helpers.js
> +        //the special cases with the unique regex values
FYI, EXCEL does not allow a user to assign match_mode to 2 and allow for BS. I was initially desigining arround the fact that I had to accommodate BS. Ill re-write it using the function you mentioned

2021-11-04 10:15 UTC, closed without merging