Lido app/marcus/xlookup
Lido-App/fast-formula-parser pull request #21
Opened 2021-11-05 09:53 UTC by marhong2

XLOOKUP is done, I also added WC match to the dependency list

2021-11-05 10:00 UTC, tyleradams requested changes
Looking good!

2021-11-05 10:00 UTC, tyleradams commented on formulas/helpers.js
> +      //EXCEL uses ~ instead of \ for their escape character, so we replace all instances of ~ with \ so that we can use a regex comparison with wcmatch
Oh slick

2021-11-08 06:43 UTC, marhong2 commented
Updated @tyleradams

2021-11-08 23:53 UTC, merged

2021-11-08 23:53 UTC, tyleradams commented
Looks good to me!

2021-12-23 14:52 UTC, mary-tung commented
Is there any reason why XLOOKUP() wouldn't be showing up in our app? Looks like all the other recently added formulas are working fine

![image](https://user-images.githubusercontent.com/55412432/147256677-5a65d92b-7b84-4e54-9d2a-099c7b2925f9.png)

2021-12-23 17:14 UTC, tyleradams commented
https://linear.app/trylido/issue/LIDO-3340/document-these-methods XLOOKUP
is on the list

On Thu, Dec 23, 2021 at 9:52 AM mary-tung ***@***.***> wrote:

> Is there any reason why XLOOKUP() wouldn't be showing up in our app? Looks
> like all the other recently added formulas are working fine
>
> [image: image]
> <https://user-images.githubusercontent.com/55412432/147256677-5a65d92b-7b84-4e54-9d2a-099c7b2925f9.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Lido-App/fast-formula-parser/pull/21#issuecomment-1000354952>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDXQYKSMF46QSHVGYFEVS3USMZTPANCNFSM5HNOLY6A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>