Lido app/marcus/json
Lido-App/fast-formula-parser pull request #55
Opened 2021-12-27 06:40 UTC by marhong2

Had to create new PR, b/c recent pushes to master were showing.

2021-12-27 06:43 UTC, marhong2 commented
Code for converting to JSON:


const tests = require('./TESTS.json');
    saveTests: (TestCase, type) => {
        const json = (tests == null)? {} : tests,
              functions = {},
              funs = Object.keys(TestCase);
        funs.forEach(fun => {
            const formulaValuePairs = {};
            fun.forEach(formula => {
                formulaValuePairs[formula] = TestCase[fun][formula]
            })
            functions[fun] = formulaValuePairs
        })
        json[type] = formulaValuePairs;

        fs.writeFile(file, JSON.stringify(json), function (err) {
            if (err) throw err;
        });
    }

2021-12-27 06:47 UTC, marhong2 commented
Note: Yarn.lock changed. I am assuming b/c I imported Sinon to fake out the system clock

2021-12-28 19:06 UTC, tyleradams commented on test/formulas/allSheets.js
> +module.exports = {
Put this in the JSON for each test. Each test should have a "sheets" param.

2021-12-28 19:08 UTC, tyleradams commented on test/utils.js
> +                    if(formula === "HOUR(NOW())")
Override the date function so it's deterministic.
https://stackoverflow.com/questions/1976968/change-browser-time-to-test-return-value-of-date

2021-12-28 19:09 UTC, tyleradams commented on test/utils.js
> +            now = new Date();
Use 2020-01-01T00:00:00Z as now so it's determinstic, it's the whole reason why we're mocking out the clock

2021-12-30 03:58 UTC, tyleradams commented on formulas/error.js
> +  switch(str) {
Use a map.

2021-12-30 04:02 UTC, tyleradams requested changes
Looking good!

2021-12-30 04:02 UTC, tyleradams commented on test/formulas/master.js
> +    data.map((row, rowIndex) => row.map((value, colIndex) => {
If you don't use the result, use a forEach.

2021-12-30 04:02 UTC, tyleradams commented on test/formulas/master.js
> +            return data[ref.row - 1][ref.col - 1]
1 index the data to make the code simpler.

2021-12-30 04:02 UTC, tyleradams commented on test/formulas/master.js
> +        //used in date, engineering, logical,
Irrelevant and subject to change

2021-12-30 04:02 UTC, tyleradams commented on test/formulas/master.js
> +        onVariable: name => {
Fold variables into the json file per test.

2021-12-30 04:59 UTC, tyleradams commented on formulas/error.js
> +  const map = {
make sure it's in the map!

2021-12-30 04:59 UTC, tyleradams commented on test/formulas/index.js
> +            return json[testName]["ON_VARIABLES"][name]
name it variables and keep it lower_snake_case

2021-12-30 09:40 UTC, marhong2 commented
const funs = Object.keys(TestCase);
        funs.forEach(fun => {
            const formulas = Object.keys(TestCase[fun]);
            formulas.forEach(formula => {
                let test = {}
                let expected = TestCase[fun][formula];
                if(expected.name){
                    expected = expected.name   
                }
                test["sheet"] = sheet
                test["expectedValue"] = expected 
                test["formula"] = formula
                json[formula] = test
            })
        })
        fs.appendFile('tests.json', JSON.stringify(json), (err) => {

2021-12-30 18:45 UTC, tyleradams commented on formulas/error.js
> +  if(map[str] != null)
if(str in map)

2021-12-30 18:45 UTC, tyleradams commented on formulas/error.js
> +  return 0
Why 0

2021-12-30 18:46 UTC, tyleradams reviewed
Why is yarn lock changing?

2021-12-31 04:42 UTC, marhong2 commented
> 

I import a new library (Sinon) If this is not enough to explain the changes I can remake the code

2021-12-31 20:05 UTC, jmorganmartin commented on test/formulas/index.js
> +                data[rowIndex][colIndex] = FormulaError.stringToError(value);
Looking at how `stringToError()` is used, you might be able to remove it entirely and instead just check `FormulaError.errorMap.has(value)` and/or `FormulaError.errorMap.get(value)`

`FormulaError.errorMap` stores all the "generic" errors that are checked in `stringToError()`.

2021-12-31 20:07 UTC, jmorganmartin commented
> > 
> 
> I import a new library (Sinon) If this is not enough to explain the changes I can remake the code (create new branch -> copy old code -> check to see if the changes to yarn.lock are the same)

`jscodeshift` is also added on this PR. It has dependencies on a bunch of newer versions of babel stuff, which constitute the majority of the changes to `yarn.lock`.

2022-01-02 02:03 UTC, tyleradams commented on test/formulas/index.js
> +            if(FormulaError.errorMap.has(value))
Nice!

2022-01-02 02:04 UTC, tyleradams commented on test/formulas/index.js
> +Object.keys(json).map((testName) => test(testName))
You should guard this so it doesn't run by default. idk if you want this or something else as I'm unfamiliar with this part of jest.
https://stackoverflow.com/questions/4981891/node-js-equivalent-of-pythons-if-name-main

2022-01-10 02:50 UTC, tyleradams commented on test/formulas/index.js
> +                // For FormulaError
Remove comment

2022-01-11 03:07 UTC, tyleradams approved these changes

2022-01-11 03:20 UTC, merged