LIDO-1740
Lido-App/fast-formula-parser pull request #82
Opened 2022-04-08 07:05 UTC by marhong2

Created INDIRECT

2022-04-11 02:11 UTC, tyleradams requested changes
@sahilgoyal2151  for quality assurance please verify that the  test expecting values match the behavior in Google Sheets

2022-04-11 02:11 UTC, tyleradams commented on grammar/utils.js
> +        throw "Unreachable Code Error"
This error message should include the value of cells so we can see what value of cells cause a unreachable code error

2022-04-25 01:56 UTC, mary-tung approved these changes

2022-05-02 23:55 UTC, tyleradams approved these changes

2022-05-16 21:45 UTC, closed without merging