LIDO-1677
Lido-App/fast-formula-parser pull request #89
Opened 2022-04-22 11:01 UTC by marhong2

2022-05-02 23:55 UTC, tyleradams requested changes

2022-05-02 23:55 UTC, tyleradams commented on formulas/functions/statistical.js
> +      if(idx % 2 == 0 && typeof accepted != "object")
=== and !==

2022-05-02 23:55 UTC, tyleradams commented on formulas/functions/statistical.js
> +       const allTrue = criteria_ranges.reduce((prev, curr, criteriaIdx) => {
use criteria_ranges.every

2022-05-18 18:52 UTC, tyleradams approved these changes

2022-05-18 18:52 UTC, tyleradams commented on formulas/functions/statistical.js
> +       }, true)
This is unneeded every takes in one parameter

2022-05-18 18:52 UTC, tyleradams commented
@PrateekshaDubey can you verify the test cases are correct?

2022-05-18 21:28 UTC, tyleradams approved these changes

2022-05-18 21:33 UTC, merged

2022-05-19 12:13 UTC, PrateekshaDubey commented
@tyleradams I have verified the test cases those are there in the Microsoft support document attached to Linear Ticket (LIDO - 1677), on high level those seems correct, more insight can be provided while executing these on particular functionality.